# Generated by Django 6.0.5 on 2026-05-14 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MapArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("north", models.FloatField()),
                ("south", models.FloatField()),
                ("east", models.FloatField()),
                ("west", models.FloatField()),
                ("grid_size_meters", models.PositiveIntegerField()),
                ("source", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="map_areas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="GridCell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_index", models.PositiveIntegerField()),
                ("col_index", models.PositiveIntegerField()),
                ("north", models.FloatField()),
                ("south", models.FloatField()),
                ("east", models.FloatField()),
                ("west", models.FloatField()),
                ("initial_score", models.FloatField(default=0)),
                ("average_user_score", models.FloatField(default=0)),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("calculated_score", models.FloatField(default=0)),
                ("score_updated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grid_cells",
                        to="maps.maparea",
                    ),
                ),
            ],
            options={
                "ordering": ["area", "row_index", "col_index"],
            },
        ),
        migrations.AddConstraint(
            model_name="maparea",
            constraint=models.CheckConstraint(
                condition=models.Q(("north__gt", models.F("south"))),
                name="map_area_north_gt_south",
            ),
        ),
        migrations.AddConstraint(
            model_name="maparea",
            constraint=models.CheckConstraint(
                condition=models.Q(("east__gt", models.F("west"))),
                name="map_area_east_gt_west",
            ),
        ),
        migrations.AddConstraint(
            model_name="maparea",
            constraint=models.CheckConstraint(
                condition=models.Q(("grid_size_meters__gt", 0)),
                name="map_area_grid_size_meters_gt_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="gridcell",
            constraint=models.UniqueConstraint(
                fields=("area", "row_index", "col_index"),
                name="unique_grid_cell_position_per_area",
            ),
        ),
    ]
