# Generated by Django 6.0.5 on 2026-05-29 03:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0003_mapareashare"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="maparea",
            name="region_feature_level",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "初期値"),
                    (1, "ありふれた地域"),
                    (2, "普通の地域"),
                    (3, "特徴的な地域"),
                ],
                default=0,
            ),
        ),
        migrations.AddConstraint(
            model_name="maparea",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("region_feature_level__gte", 0), ("region_feature_level__lte", 3)
                ),
                name="map_area_region_feature_level_between_0_and_3",
            ),
        ),
    ]
