# Generated by Django 6.0.5 on 2026-05-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0004_maparea_region_feature_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="maparea",
            name="initial_score_mode",
            field=models.CharField(
                choices=[("manual", "Manual"), ("auto", "Auto")],
                default="manual",
                max_length=20,
            ),
        ),
    ]
