# Generated by Codex on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0005_maparea_initial_score_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="gridcell",
            name="auto_score_breakdown",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
