# Generated by Django 6.0.5 on 2026-06-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0006_gridcell_auto_score_breakdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="maparea",
            name="grid_generation_attempt_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="maparea",
            name="grid_generation_error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="maparea",
            name="grid_generation_finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="maparea",
            name="grid_generation_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="maparea",
            name="grid_generation_status",
            field=models.CharField(
                choices=[
                    ("pending", "作成待ち"),
                    ("running", "作成中"),
                    ("completed", "作成完了"),
                    ("fallback_completed", "標準値で作成完了"),
                    ("failed", "作成失敗"),
                ],
                default="completed",
                max_length=30,
            ),
        ),
    ]
