# Generated by Django 6.0.5 on 2026-06-26 03:41

from django.db import migrations, models
from django.db.models import Max


def populate_map_grid_dimensions(apps, schema_editor):
    MapArea = apps.get_model("maps", "MapArea")
    GridCell = apps.get_model("maps", "GridCell")

    grid_sizes = (
        GridCell.objects.values("area_id")
        .annotate(
            max_row_index=Max("row_index"),
            max_col_index=Max("col_index"),
        )
        .order_by()
    )
    for grid_size in grid_sizes:
        MapArea.objects.filter(id=grid_size["area_id"]).update(
            map_grid_rows=grid_size["max_row_index"] + 1,
            map_grid_cols=grid_size["max_col_index"] + 1,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("maps", "0007_maparea_grid_generation_attempt_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="maparea",
            name="map_grid_cols",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="maparea",
            name="map_grid_rows",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(
            populate_map_grid_dimensions,
            migrations.RunPython.noop,
        ),
    ]
